%% ========================================================================
%  FUNCTION: Create complete figure for one site and one depth
%% ========================================================================
function create_site_depth_figure(site_name, depth_num, ...
                                   data_normal_nee, data_normal_moisture, data_normal_temp, ...
                                   data_extreme_nee, data_extreme_moisture, data_extreme_temp, ...
                                   data_deficient_nee, data_deficient_moisture, data_deficient_temp, ...
                                   xtime_normal, ztime_normal, ytime_normal, ...
                                   xtime_extreme, ztime_extreme, ytime_extreme, ...
                                   xtime_deficient, ztime_deficient, ytime_deficient, ...
                                   commonOptions, monthTicks, monthLabels, grayColor, arc_colors, arc_styles)
    
    % Create figure
    figure('Name', sprintf('%s: NEE vs Soil Moisture/Temperature - Depth %d', site_name, depth_num), ...
           'Position', [100, 100, 1200, 800]);
    t = tiledlayout(3, 3, 'TileSpacing', 'tight', 'Padding', 'tight');
    
    % Depth label for display
    depth_label = sprintf('\\theta_{%d}', depth_num);
    tsoil_label = sprintf('Tsoil_{%d}', depth_num);
    
    % Abbreviated site name for legends
    site_abbr = site_name(1:3);
    
    % ===== ROW 1: NORMAL CONDITION =====
    nexttile;
    create_wtc_subplot(data_normal_nee, data_normal_moisture, ...
                      sprintf('a) %s: NEE vs %s (Normal)', site_name, depth_label), ...
                      'Periods (nights)', '', commonOptions, monthTicks, monthLabels);
    
    nexttile;
    create_wtc_subplot(data_normal_nee, data_normal_temp, ...
                      sprintf('b) %s: NEE vs %s (Normal)', site_name, tsoil_label), ...
                      'Periods (nights)', '', commonOptions, monthTicks, monthLabels);
    
    nexttile;
    create_coherence_subplot(xtime_normal, ztime_normal, ytime_normal, ...
                            sprintf('c) GC: NEE-%s & NEE-%s (Normal)', depth_label, tsoil_label), ...
                            '', true, ...
                            sprintf('%s-%s', site_abbr, depth_label), ...
                            sprintf('%s-%s', site_abbr, tsoil_label), ...
                            grayColor, arc_colors, arc_styles);
    
    % ===== ROW 2: SURPLUS (EXTREME) CONDITION =====
    nexttile;
    create_wtc_subplot(data_extreme_nee, data_extreme_moisture, ...
                      sprintf('d) %s: NEE vs %s (Surplus)', site_name, depth_label), ...
                      'Periods (nights)', '', commonOptions, monthTicks, monthLabels);
    
    nexttile;
    create_wtc_subplot(data_extreme_nee, data_extreme_temp, ...
                      sprintf('e) %s: NEE vs %s (Surplus)', site_name, tsoil_label), ...
                      'Periods (nights)', '', commonOptions, monthTicks, monthLabels);
    
    nexttile;
    create_coherence_subplot(xtime_extreme, ztime_extreme, ytime_extreme, ...
                            sprintf('f) GC: NEE-%s & NEE-%s (Surplus)', depth_label, tsoil_label), ...
                            '', false, '', '', grayColor, arc_colors, arc_styles);
    
    % ===== ROW 3: DEFICIENT CONDITION =====
    nexttile;
    create_wtc_subplot(data_deficient_nee, data_deficient_moisture, ...
                      sprintf('g) %s: NEE vs %s (Deficient)', site_name, depth_label), ...
                      'Periods (nights)', 'Years', commonOptions, monthTicks, monthLabels);
    
    nexttile;
    create_wtc_subplot(data_deficient_nee, data_deficient_temp, ...
                      sprintf('h) %s: NEE vs %s (Deficient)', site_name, tsoil_label), ...
                      'Periods (nights)', 'Years', commonOptions, monthTicks, monthLabels);
    
    nexttile;
    create_coherence_subplot(xtime_deficient, ztime_deficient, ytime_deficient, ...
                            sprintf('i) GC: NEE-%s & NEE-%s (Deficient)', depth_label, tsoil_label), ...
                            'Coherence', false, '', '', grayColor, arc_colors, arc_styles);
end
